apiVersion: v1
kind: Service
metadata:
  name: client
spec:
  selector:
    app: react-basic-2021-client
  ports:
    - protocol: 'TCP'
      port: 3000
      targetPort: 3000
  type: LoadBalancer
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: react-basic-2021-client-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: react-basic-2021-client
      tier: client
  template:
    metadata:
      labels:
        app: react-basic-2021-client
        tier: client
    spec:
      containers:
        - name: client
          image: johnny1992/react-basic-2021-client:3
          imagePullPolicy: Always
