version: '3.8'
services:
  server:
    build:
      context: ./server
      dockerfile: ./docker/server
    ports:
      - '5000:5000'
  client:
    build:
      context: ./client
      dockerfile: ./docker/client
    ports:
      - '3001:3000'
    volumes:
      - ./client/src:/app/src
    stdin_open: true
    tty: true
