version: '3.8'
services:
  server:
    build: ./server
    ports:
      - '5000:5000'
  client:
    build: ./client
    ports:
      - '3001:3000'
    volumes:
      - ./client/src:/app/src
    stdin_open: true
    tty: true
